### PR TITLE
Update 'npm run clean:dist'

### PR DESCRIPTION
**Pull request by 408796571**
should add "run" before "clean:dist"

### CODE REVIEW

**Comment by sgbj** [comment]
Thanks for your contribution.

**Comment by 408796571** [comment]
Could you provide a guide on deploying this project to IIS ? I'm having trouble wrapping this around since this is my first time trying out Angular 2 with .NET. It would be really appreciated.

I have been getting the following error.
"Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'".

**Comment by sgbj** [comment]
I can work on a guide, but it'll probably be a couple days before I can start on it. If you have access to the IIS server's file system, and you're able to run the project locally without errors, then, you should be able to copy your node_modules folder over to the website directory on the IIS server.

Or change the publishOptions section of your project.json to look like this:

```json
  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config",
      "node_modules"      <------ add this
    ],
    "exclude": [
      "wwwroot/src",
      "wwwroot/e2e"
    ]
  },
```

And then right click on your project in VS and click publish, and follow [this guide](https://docs.microsoft.com/en-us/aspnet/core/publishing/iis) to deploy the app to IIS.

**Comment by 408796571** [comment]
I really appreciate your fast reply. I actually did try to include node_modules as discussed in previous thread, but it didn't work for me. I'm actually trying out this seed project https://github.com/damienbod/Angular2WebpackVisualStudio. However this one does not have testing suit as well as HMR like yours do.

**Pull request merged**
